### ISSUE TITLE
Fatal error calling bw_backtrace()

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-loader#4]
tal error: Uncaught Error: Call to undefined function bw_backtrace() in /home/bworguk/public_html/wp-content/mu-plugins/oik-loader-mu.php:155 Stack trace: #0 /home/bworguk/public_html/wp-includes/class-wp-hook.php(286): oik_loader_option_active_plugins(Array, 'active_plugins') #1 /home/bworguk/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /home/bworguk/public_html/wp-includes/option.php(152): apply_filters('option_active_p...', Array, 'active_plugins') #3 /home/bworguk/public_html/wp-admin/includes/plugin.php(509): get_option('active_plugins', Array) #4 /home/bworguk/public_html/wp-content/plugins/caxton/inc/wp-sdk/start.php(189): is_plugin_active('caxton/caxton.p...') #5 /home/bworguk/public_html/wp-content/plugins/caxton/caxton.php(39): require_once('/home/bworguk/p...') #6 /home/bworguk/public_html/wp-content/plugins/caxton/caxton.php(61): caxton_fs() #7 /home/bworguk/public_html/wp-settings.php(310): include_once('/home/bworguk/p...') #8 /home/bworguk/public_html/wp-config.php(113) in /home/bworguk/public_html/wp-content/mu-plugins/oik-loader-mu.php on line 155

**Comment by bobbingwide** [comment]
That’s interesting I made a commit but forgot to reference the issue so the change is not shown. I applied it directly using oik-batch’s admin interface that uses git pull, then redeployed using oik-loader’s admin. It worked a treat. Apologies to anyone who had problems.

**Comment by bobbingwide** [comment]
Fixed in https://github.com/bobbingwide/oik-loader/commit/7279ad0747060853cda58c7384fd78b9a00ffdca
